services:
  laravel.test:
    build:
      context: './vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - pgsql
      - mailpit
  pgsql:
    image: 'postgres:17'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'
      - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail

  #   pgadmin:
  #     image: dpage/pgadmin4
  #     restart: always
  #     ports:
  #       - '5050:80' # Access pgAdmin at http://localhost:5050
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL:-admin@admin.com}'
  #       PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD:-admin}'
  #       # PGADMIN_CONFIG_AUTHENTICATION_METHOD: 'ldap' # This disables the login screen
  #     depends_on:
  #       - pgsql
  #     networks:
  #       - sail
  #     volumes:
  #       - 'sail-pgadmin:/var/lib/pgadmin'
  #       - ./pgadmin/servers.json:/var/lib/pgadmin/servers.json # Correct path

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080' # Access Adminer at http://localhost:8080
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
    depends_on:
      - pgsql
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local
#   sail-pgadmin:
#     driver: local
